/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ENLCSRVDRS_H_RPCGEN
#define _ENLCSRVDRS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define comunicacion_servidores 0x20000002
#define comunicacion_servidores_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define validar_codigo_usuario 1
extern  int * validar_codigo_usuario_1(char **, CLIENT *);
extern  int * validar_codigo_usuario_1_svc(char **, struct svc_req *);
extern int comunicacion_servidores_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define validar_codigo_usuario 1
extern  int * validar_codigo_usuario_1();
extern  int * validar_codigo_usuario_1_svc();
extern int comunicacion_servidores_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ENLCSRVDRS_H_RPCGEN */
