/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "enlcSrvdrs.h"

int *
validar_codigo_usuario_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result = 0;

	printf("\nSolicitud de validacion de codigo %s", (*argp)); 
	fflush(stdout);

	return &result;
}
