/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "adminSvdrGU.h"

bool_t
xdr_adminSvdrGU (XDR *xdrs, adminSvdrGU *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->login, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->clave, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_usuario (XDR *xdrs, usuario *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->codigo, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->nombres, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->apellidos, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->rol, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_adminGU (XDR *xdrs, adminGU *objp)
{
	register int32_t *buf;

	 if (!xdr_adminSvdrGU (xdrs, objp))
		 return FALSE;
	return TRUE;
}
