/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADMINSVDRGU_H_RPCGEN
#define _ADMINSVDRGU_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_LOGIN 16
#define MAX_CLAVE 16
#define MAX_CODIGO 9
#define MAX_NOMBRES 20
#define MAX_APELLIDOS 20
#define MAX_ROL 15

struct adminSvdrGU {
	char login[MAX_LOGIN];
	char clave[MAX_CLAVE];
};
typedef struct adminSvdrGU adminSvdrGU;

struct usuario {
	char codigo[MAX_CODIGO];
	char nombres[MAX_NOMBRES];
	char apellidos[MAX_APELLIDOS];
	char rol[MAX_ROL];
};
typedef struct usuario usuario;

typedef adminSvdrGU adminGU;


#define gestion_usuarios 0x20000003
#define gestion_usuarios_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define acceso_admin 1
extern  int * acceso_admin_1(adminGU *, CLIENT *);
extern  int * acceso_admin_1_svc(adminGU *, struct svc_req *);
#define ingreso_usuario 2
extern  int * ingreso_usuario_1(usuario *, CLIENT *);
extern  int * ingreso_usuario_1_svc(usuario *, struct svc_req *);
#define modificar_usuario 3
extern  int * modificar_usuario_1(usuario *, CLIENT *);
extern  int * modificar_usuario_1_svc(usuario *, struct svc_req *);
#define obtener_usuario 4
extern  usuario * obtener_usuario_1(char **, CLIENT *);
extern  usuario * obtener_usuario_1_svc(char **, struct svc_req *);
#define eliminar_usuario 5
extern  int * eliminar_usuario_1(char **, CLIENT *);
extern  int * eliminar_usuario_1_svc(char **, struct svc_req *);
extern int gestion_usuarios_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define acceso_admin 1
extern  int * acceso_admin_1();
extern  int * acceso_admin_1_svc();
#define ingreso_usuario 2
extern  int * ingreso_usuario_1();
extern  int * ingreso_usuario_1_svc();
#define modificar_usuario 3
extern  int * modificar_usuario_1();
extern  int * modificar_usuario_1_svc();
#define obtener_usuario 4
extern  usuario * obtener_usuario_1();
extern  usuario * obtener_usuario_1_svc();
#define eliminar_usuario 5
extern  int * eliminar_usuario_1();
extern  int * eliminar_usuario_1_svc();
extern int gestion_usuarios_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_adminSvdrGU (XDR *, adminSvdrGU*);
extern  bool_t xdr_usuario (XDR *, usuario*);
extern  bool_t xdr_adminGU (XDR *, adminGU*);
extern  bool_t xdr_usuario (XDR *, usuario*);

#else /* K&R C */
extern bool_t xdr_adminSvdrGU ();
extern bool_t xdr_usuario ();
extern bool_t xdr_adminGU ();
extern bool_t xdr_usuario ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADMINSVDRGU_H_RPCGEN */
