/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "adminSvdrGU.h"

bool_t
xdr_adminSvdrGU (XDR *xdrs, adminSvdrGU *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->login, MAX_LOGIN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->clave, MAX_CLAVE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_usuario (XDR *xdrs, usuario *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->codigo, MAX_CODIGO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombres, MAX_NOMBRES,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->apellidos, MAX_APELLIDOS,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->rol, MAX_ROL,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_adminGU (XDR *xdrs, adminGU *objp)
{
	register int32_t *buf;

	 if (!xdr_adminSvdrGU (xdrs, objp))
		 return FALSE;
	return TRUE;
}
