/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "adminSvdrGU.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#define ARCHIVO_ADMIN "admin.txt"
#define MAXTAM_LOGIN 15
#define MINTAM_LOGIN 8
#define MAXTAM_CLAVE 15
#define MINTAM_CLAVE 8


void crearFichero() {
	FILE * ficheroAdmin = fopen(ARCHIVO_ADMIN, "a+b");
	if (ficheroAdmin != NULL) {
		adminGU admin;
		strcpy(admin.login, "administrador");
		strcpy(admin.clave, "administrador");
		fwrite(&admin, sizeof(adminGU), 1, ficheroAdmin);
		fclose(ficheroAdmin);
	} else {
		printf("\nNo se pudó crear el fichero admin.txt\n");
	}
}

adminGU  obtenerCredencial() {	
	FILE * ficheroAdmin = fopen(ARCHIVO_ADMIN, "rb");
	adminGU  resultado;
	if (ficheroAdmin != NULL) {
		fread(&resultado, sizeof(adminGU), 1, ficheroAdmin);
		fclose(ficheroAdmin);
	} else {
		printf("\nError al accesar al fichero de administrador");
	}
	return resultado;
}

int *
acceso_admin_1_svc(adminGU *argp, struct svc_req *rqstp)
{
	printf("\nSolicitud acceso administrador %s %s", (*argp).login + 1, (*argp).clave); 
	static int result = 0;
	adminGU  admin = obtenerCredencial();
	if (strcmp(admin.login,(*argp).login) == 0 && strcmp(admin.clave,(*argp).clave) == 0) {
		result = 1;
	}
	fflush(stdout);
	return &result;
}

int *
ingreso_usuario_1_svc(usuario *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
modificar_usuario_1_svc(usuario *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

usuario *
obtener_usuario_1_svc(char **argp, struct svc_req *rqstp)
{
	static usuario  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
eliminar_usuario_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
