/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "adminSvdrGU.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#define ARCHIVO_ADMIN "admin.txt"
#define MAXTAM_LOGIN 15
#define MINTAM_LOGIN 8
#define MAXTAM_CLAVE 15
#define MINTAM_CLAVE 8

void obtenerCredencial(char * buffer, int tamanioBuffer) {
	int descriptor = open(ARCHIVO_ADMIN, O_RDONLY);
	if (descriptor != -1) {
		read(descriptor, buffer, tamanioBuffer);
		close(descriptor);
	} else {
		printf("\nNo se pudo validar las credenciales del administrador\n");
	}
}

int *
acceso_admin_1_svc(adminGU *argp, struct svc_req *rqstp)
{	
	printf("\nSolicitud acceso administrador %s %s", (*argp).login + 1, (*argp).clave); 
	static int  result = 0;
	int tamanioBuffer = MAXTAM_LOGIN + MAXTAM_CLAVE + 3;
	char registroAdmin[tamanioBuffer], * auxLogin = (char *)malloc(sizeof(char) * MAXTAM_LOGIN), * auxClave = (char *)malloc(sizeof(char) * MAXTAM_CLAVE), * auxBuffer = (char *)malloc(sizeof(char) * tamanioBuffer);
	memset(&registroAdmin, ' ', tamanioBuffer);
	memset(auxBuffer, ' ', tamanioBuffer);
	memset(auxClave, ' ', MAXTAM_CLAVE);
	obtenerCredencial(registroAdmin, tamanioBuffer);
	auxBuffer = strtok(registroAdmin, ";");
	strcpy(auxLogin, auxBuffer);
	auxBuffer = strtok(NULL, ";");
	strcpy(auxClave, auxBuffer);
	printf("\nLogin: %s long: %d | auxLogin %s long: %d", (*argp).login, strlen((*argp).login), auxLogin, strlen(auxLogin));
	if ((strcmp(auxLogin, (*argp).login) == 0) && (strcmp(auxClave, (*argp).clave) == 0)) {
		printf("\nAcceso concedido");
		result = 1;
	}
	fflush(stdout);
	return &result;
}

int *
ingreso_usuario_1_svc(usuario *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
modificar_usuario_1_svc(usuario *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

usuario *
obtener_usuario_1_svc(char **argp, struct svc_req *rqstp)
{
	static usuario  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
eliminar_usuario_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
