/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "accesoUsrs.h"
#include <stdio.h>

void
acceso_usuarios_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char * solicitud_entrada_1_arg;
	char * *result_2;
	char * solicitud_salida_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, acceso_usuarios, acceso_usuarios_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	int opcion;
	
	do {
		printf("\n ============= MENU ==============\n");
		printf("\n\tOpciones de usuario");
		printf("\n\t 1. Entrar a instalaciones");
		printf("\n\t 2. Salir de instalaciones");
		printf("\n\t 0. Detener aplicación");
		printf("\n\t Elija una opcion > ");
		scanf("%d", &opcion);		
		system("clear");
		switch (opcion) {
			case 0: 
				printf("\n Fin del programa\n");
			break;
			case 1:
				printf("\n Ingrese su codigo > ");
				scanf("%s", solicitud_entrada_1_arg);
				result_1 = solicitud_entrada_1(&solicitud_entrada_1_arg, clnt);
				if (result_1 == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					printf("\n%s\n", *result_1);
				}
			break;
			case 2:
				printf("\n Ingrese su codigo > ");
				scanf("%s", solicitud_salida_1_arg);
				result_2 = solicitud_salida_1(&solicitud_salida_1_arg, clnt);
				if (result_2 == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					printf("\n%s\n", *result_2);
				}					
			break;
			default:
				printf("\nOpcion incorrecta. Intente de nuevo");
			break;
		}
	} while (opcion != 0);
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	acceso_usuarios_1 (host);
exit (0);
}
