/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ACCESOUSRS_H_RPCGEN
#define _ACCESOUSRS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define acceso_usuarios 0x20000001
#define acceso_usuarios_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define solicitud_entrada 1
extern  char ** solicitud_entrada_1(char **, CLIENT *);
extern  char ** solicitud_entrada_1_svc(char **, struct svc_req *);
#define solicitud_salida 2
extern  char ** solicitud_salida_1(char **, CLIENT *);
extern  char ** solicitud_salida_1_svc(char **, struct svc_req *);
extern int acceso_usuarios_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define solicitud_entrada 1
extern  char ** solicitud_entrada_1();
extern  char ** solicitud_entrada_1_svc();
#define solicitud_salida 2
extern  char ** solicitud_salida_1();
extern  char ** solicitud_salida_1_svc();
extern int acceso_usuarios_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ACCESOUSRS_H_RPCGEN */
